apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.elasticsearch.name }}-svc"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.elasticsearch.name }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name }}
  clusterIP: None
  ports:
    - port: {{ .Values.elasticsearch.ports.http }} 
      name: rest
    - port: {{ .Values.elasticsearch.ports.transport }} 
      name: inter-node