replicaCount: 1
revisionHistoryLimit: 10

deployment:
  annotations: {}
  labels: {}

image:
  repository: "k8s.gcr.io/cluster-autoscaler"
  tag: "v1.21.0"
  pullPolicy: "IfNotPresent"

cloudProvider: "aws"
awsRegion: "us-east-1"
autoDiscovery:
  clusterName: "redhat-eks-cluster-dev"
  namespace: "kube-system"
  tags:
    - "tag1=value1"
    - "tag2=value2"
  labels: []
  roles: []
autoscalingGroups:
  - name: "my-auto-scaling-group"
    minSize: 1
    maxSize: 5
    instanceType: "t2.micro"
    region: "us-east-1"

priorityClassName: "high-priority"
dnsPolicy: "ClusterFirst"
hostNetwork: false

initContainers: []

podAnnotations: {}

podLabels: {}

updateStrategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

extraArgs: 
  - "v"
  - "4"

extraEnv: 
  CUSTOM_ENV: "value"

envFromSecret: ""
envFromConfigMap: ""

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

containerSecurityContext: {}

affinity: {}
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []

securityContext: {}

extraVolumeSecrets: {}
extraVolumeMounts: []

cloudConfigPath: "/etc/cloudconfig"

serviceAccountName: "cluster-autoscaler-sa"

# Add this to your values.yaml file
vpa:
  enabled: false  # Set to true if you want to enable Vertical Pod Autoscaler
