apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=   # Base64-encoded "admin"
  admin-password: cHJvbS1vcGVyYXRvcg==  # Base64-encoded "prom-operator"
