apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-init-script
  namespace: monitoring
data:
  fetch-secrets.sh: |
    #!/bin/sh
    SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id grafana-credentials --query SecretString --output text)
    export GF_SECURITY_ADMIN_USER=$(echo $SECRET_JSON | jq -r .admin-user)
    export GF_SECURITY_ADMIN_PASSWORD=$(echo $SECRET_JSON | jq -r .admin-password)
    exec /run.sh  # Start Grafana
