# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: grafana-service-account
#   namespace: monitoring
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: monitoring
#   name: grafana-secrets-role
# rules:
#   - apiGroups: [""]
#     resources: ["secrets"]
#     verbs: ["get", "list"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: grafana-secrets-binding
#   namespace: monitoring
# subjects:
#   - kind: ServiceAccount
#     name: grafana-service-account
#     namespace: monitoring
# roleRef:
#   kind: Role
#   name: grafana-secrets-role
#   apiGroup: rbac.authorization.k8s.io
