apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-secrets-provider
  namespace: monitoring  # Namespace where Thanos is running
spec:
  provider: aws  # AWS Secrets Manager provider
  parameters:
    objects: |
      - objectName: "grafana_secrets"  # The name of the secret in AWS Secrets Manager
        jmesPath:
          - path: "adminUser"  # Key in AWS Secret for S3 access key
            objectAlias: "adminUser"  # File name in the container
          - path: "adminPassword"  # Key in AWS Secret for S3 secret key
            objectAlias: "adminPassword"  # File name in the container