---
### Since EKS manages control plana, we want to disable monitoring for etcd, scheduler and contrtoller.
defaultRules:
  rules:
    etcd: false
    kubeScheduler: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
### Also add custom labels. This label will be used by prometheus operator to select service monitor objects e.g. postgres
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: devops
### Common labels. Add the same lables that you used periously. 
### If you will not add it prometheus operator will ignore default service monitors created by this helm chart. And prometheus target options would be empty.
commonLabels:
  prometheus: devops

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.togzhanborangali.click
    tls:
      - secretName: grafana-tls-secret
        hosts:
          - grafana.togzhanborangali.click
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: letsencrypt-prod  # Use the issuer to request a certificate

  admin:
    existingSecret: grafana-secrets  # This tells Helm to use the Kubernetes Secret
    userKey: admin-user              # Key in the secret for the username
    passwordKey: admin-password      # Key in the secret for the password

  extraEnv:
    - name: GF_SECURITY_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: grafana-secrets
          key: admin-user
    - name: GF_SECURITY_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: grafana-secrets
          key: admin-password

 

    # # To make Grafana persistent (Using Statefulset)
  # #
  # persistence:
  #   enabled: true
  #   type: sts
  #   storageClassName: "storageClassName"
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 20Gi
  #   finalizers:
  #     - kubernetes.io/pvc-protection



